# Generated by Django 3.0.4 on 2020-03-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('description', models.TextField()),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('rating', models.FloatField()),
                ('url', models.URLField()),
            ],
        ),
    ]
