# Generated by Django 3.0.4 on 2020-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ico',
            name='ends',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='ico',
            name='starts',
            field=models.CharField(max_length=16),
        ),
    ]
