# Generated by Django 3.0.4 on 2020-05-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icoapp', '0003_auto_20200526_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ico',
            name='user',
        ),
    ]
