# Generated by Django 3.0.4 on 2020-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoapp', '0005_ico_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ico',
            name='period',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
