# Generated by Django 3.0.4 on 2020-05-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoapp', '0006_ico_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ico',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
