# Generated by Django 3.0.4 on 2020-05-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoapp', '0008_auto_20200529_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ico',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
